apiVersion: v2
name: nginx-ingress-controller
description: A Helm chart for deploying NGINX Ingress Controller in GKE
type: application
version: 0.1.0
appVersion: "1.8.1"
maintainers:
  - name: Amol Ghadge
keywords:
  - ingress
  - nginx
  - gke
dependencies:
  - name: ingress-nginx
    version: "4.7.1"
    repository: https://kubernetes.github.io/ingress-nginx
